# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and test application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.2.0
      with:
        #aws-access-key-id: ${{ secrets.AWS_GITHUB_ACTIONS_ACCESS_KEY_ID }}
        #aws-secret-access-key: ${{ secrets.AWS_GITHUB_ACTIONS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
        role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_TO_ASSUME }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --logger "trx;LogFileName=reports/test-results.trx"
    # - name: TestReport
    #   uses: dorny/test-reporter@v2
    #   if: success() || failure()    # run this step even if previous step failed
    #   with:
    #     name: NUnit Tests           # Name of the check run which will be created
    #     path: ./*/reports/test-results.trx    # Path to test results
    #     reporter: dotnet-trx        # Format of test results
